name: Release Workflow

on:
  push:
    branches:
      - setup-release-workflow  # Change to your main branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Replace with your desired Python version

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Install dependencies
      run: pip install -r requirements.txt  # Replace with your dependencies file

    - name: Check if a release exists
      id: check_release
      run: |
        latest_release=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name // "none"')
        if [ "$latest_release" == "none" ]; then
          echo "No existing release found."
          echo "::set-output name=no_release::true"
        else
          echo "Latest release is $latest_release"
          echo "::set-output name=latest_release::$latest_release"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    
    - name: Set initial version if no release exists
      id: initial_version
      if: steps.check_release.outputs.no_release == 'true'
      run: |
        initial_version="1.0.0"  # Set your desired initial version
        echo "Setting initial version to $initial_version"
        echo "::set-output name=initial_version::$initial_version"

    - name: Parse and bump version
      if: steps.check_release.outputs.no_release == 'false'
      id: bump_version
      run: |
        latest_release=$1  # Pass the latest release as an argument
        # Parse the latest version
        major_version=$(echo $latest_release | cut -d'.' -f1)
        minor_version=$(echo $latest_release | cut -d'.' -f2)
        patch_version=$(echo $latest_release | cut -d'.' -f3)
        # Increment the patch version
        new_version="$major_version.$minor_version.$((patch_version + 1))"
        echo "::set-output name=new_version::$new_version"
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        latest_version: ${{ steps.check_release.latest_release }}


    # - name: Create Git tag
    #   run: |
    #     new_version=$1  # Pass the new version as an argument
    
    #     if [ -n "$new_version" ]; then
    #       echo "Creating release for version $new_version"
    #     else
    #       new_version=$INITIAL_VERSION  # Use the initial version if no release exists
    #       echo "Creating release for initial version $new_version"
    #     fi

    #     echo "Creating Git tag for version $new_version"
    #     git tag -a "$new_version" -m "Version $new_version"
    #     git push origin "$new_version"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    #     NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
    #     INITIAL_VERSION: ${{ steps.initial_version.initial_version }}

    
    - name: Create a new release
      run: |
        new_version=$1  # Pass the new version as an argument
        initial_version=$1
    
        if [ -n "$new_version" ]; then
          echo "Creating release for version $new_version"
        else
          new_version=$INITIAL_VERSION  # Use the initial version if no release exists
          echo "Creating release for initial version $new_version"
        fi

        echo "Creating release for version $new_version"
    
        curl -X POST "https://api.github.com/repos/${{ github.repository }}/releases" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "tag_name": "'"$new_version"'",
            "name": "Release '"$new_version"'",
            "body": "Release '"$new_version"'",
            "draft": false,
            "prerelease": false
          }'
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        NEW_VERSION: ${{ steps.bump_version.outputs.new_version }}
        INITIAL_VERSION: ${{ steps.initial_version.initial_version }}
      
    

  
      
