# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    # - name: Lint with flake8
    #   run: |
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest
    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
      uses: ncipollo/release-action@v1.13.0
      with:
        # An optional flag which indicates if we should update a release if it already exists. Defaults to false.
        allowUpdates: # optional, default is 
        # An optional flag which indicates if artifact read or upload errors should fail the build.
        artifactErrorsFailBuild: # optional, default is 
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifact: # optional, default is 
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifacts: # optional, default is 
        # The content type of the artifact. Defaults to raw
        artifactContentType: # optional, default is 
        # An optional body for the release.
        body: # optional, default is 
        # An optional body file for the release. This should be the path to the file
        bodyFile: # optional, default is 
        # An optional commit reference. This will be used to create the tag if it does not exist.
        commit: # optional, default is 
        # When provided this will generate a discussion of the specified category. The category must exist otherwise this will cause the action to fail. This isn't used with draft releases
        discussionCategory: # optional, default is 
        # Optionally marks this release as a draft release. Set to true to enable.
        draft: # optional, default is 
        # Indicates if release notes should be automatically generated.
        generateReleaseNotes: # optional, default is false
        # Indicates if the release should be the "latest" release or not.
        makeLatest: # optional, default is legacy
        # An optional name for the release. If this is omitted the tag will be used.
        name: # optional, default is 
        # Indicates if the release body should be omitted.
        omitBody: # optional, default is false
        # Indicates if the release body should be omitted during updates. The body will still be applied for newly created releases. This will preserve the existing body during updates.
        omitBodyDuringUpdate: # optional, default is false
        # Indicates if the draft flag should be omitted during updates. The draft flag will still be applied for newly created releases. This will preserve the existing draft state during updates.
        omitDraftDuringUpdate: # optional, default is false
        # Indicates if the release name should be omitted.
        omitName: # optional, default is false
        # Indicates if the release name should be omitted during updates. The name will still be applied for newly created releases. This will preserve the existing name during updates.
        omitNameDuringUpdate: # optional, default is false
        # Indicates if the prerelease flag should be omitted during updates. The prerelease flag will still be applied for newly created releases. This will preserve the existing prerelease state during updates.
        omitPrereleaseDuringUpdate: # optional, default is false
        # Optionally specify the owner of the repo where the release should be generated. Defaults to current repo's owner.
        owner: # optional, default is 
        # Optionally marks this release as prerelease. Set to true to enable.
        prerelease: # optional, default is 
        removeArtifacts: # optional, default is false
        # Indicates if existing release artifacts should be replaced. Defaults to true.
        replacesArtifacts: # optional, default is true
        # Optionally specify the repo where the release should be generated. Defaults to current repo
        repo: # optional, default is 
        # When skipIfReleaseExists is enabled the action will be skipped if a non-draft release already exists for the provided tag.
        skipIfReleaseExists: # optional, default is false
        # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
        tag: # optional, default is 
        # The Github token.
        token: # optional, default is ${{ github.token }}
        # When allowUpdates is enabled, this will fail the action if the release it is updating is not a draft or a prerelease.
        updateOnlyUnreleased: # optional, default is false

    
        
